[scenario]
name = "test_town"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
verbose = false
version = 12
using_experienced_plans = false

[inputs]
events = "/home/arup/ile-de-france/cache/matsim.simulation.run__420b91e82165d6fbc00e412fadd3536d.cache/simulation_output/output_events.xml.gz"
network = "/home/arup/ile-de-france/cache/matsim.simulation.run__420b91e82165d6fbc00e412fadd3536d.cache/simulation_output/output_network.xml"
transit_schedule = "/home/arup/ile-de-france/cache/matsim.simulation.run__420b91e82165d6fbc00e412fadd3536d.cache/simulation_output/output_transitSchedule.xml"
transit_vehicles = "/home/arup/ile-de-france/cache/matsim.simulation.run__420b91e82165d6fbc00e412fadd3536d.cache/simulation_output/output_transitVehicles.xml"
plans= "/home/arup/ile-de-france/cache/matsim.simulation.run__420b91e82165d6fbc00e412fadd3536d.cache/simulation_output/output_plans.xml"
output_config_path = "/home/arup/ile-de-france/cache/matsim.simulation.run__420b91e82165d6fbc00e412fadd3536d.cache/simulation_output/output_config.xml"


[outputs]
path = "./eqasim_outputs"

[event_handlers]
link_vehicle_counts = ["car", "bus"]
stop_passenger_counts = ["bus"]
stop_passenger_waiting = ["all"]
link_passenger_counts = ["bus"]
vehicle_departure_log = ["bus"]
vehicle_passenger_log = ["bus"]
stop_to_stop_passenger_counts = ["bus"]
vehicle_stop_to_stop_passenger_counts = ["bus"]

[plan_handlers]
trip_modes = {attributes=["age"]}
trip_activity_modes = {destination_activity_filters=["work"], attributes=["age"]}
plan_modes = {attributes=["age"]}
plan_activity_modes = {destination_activity_filters=["work"], attributes=["age"]}
trip_logs = ["all"]
agent_highway_distance_logs = ["car"]
trip_highway_distance_logs = ["car"]

[post_processors]
plan_summary = ["all"]
vkt = ["car"]
trip_duration_breakdown = ["all"]
trip_euclid_distance_breakdown = ["all"]
